### ISSUE TITLE
README

### ISSUE THREAD

**Issue by ayaan-qadri** [PentW0lf/OnlineCarBooking#3]
create cool README.md

**Comment by vijay-varadarajan** [comment]
Hi, I would love to make the read me look cooler and add more content to it. Please assign this issue to me.

**Comment by Sanskritis101** [comment]
I'd like to give this a try :)

**Comment by vijay-varadarajan** [comment]
Hi, thank you for assigning this to me. I'll complete the readme asap

**Comment by ayaan-qadri** [comment]
@vijay-varadarajan there you go!

**Comment by ayaan-qadri** [comment]
> I'd like to give this a try :)

Thank you for showing your interest but @vijay-varadarajan commented before you, You can try other issue.

**Comment by vijay-varadarajan** [comment]
Getting started now

**Comment by ayaan-qadri** [comment]
It's been almost 24h no update from your side @vijay-varadarajan, If you are not gonna work on it then lemme know so that i assign to @Sanskritis101

**Comment by vijay-varadarajan** [comment]
Hi
I'm really sorry for not updating

I'm still working on it and I assure you it'll be ready within 12 more hrs

**Comment by ayaan-qadri** [comment]
> Hi
> I'm really sorry for not updating
> 
> I'm still working on it and I assure you it'll be ready within 12 more hrs

No issue, Take your time.

**Comment by vijay-varadarajan** [comment]
Hi, shall i remove the admin cred.s from the readme or should I leave it in

**Comment by ayaan-qadri** [comment]
> Hi, shall i remove the admin cred.s from the readme or should I leave it in

Ppl need admin credentials for login into admin, So keep it.

**Comment by vijay-varadarajan** [comment]
Sure, 
I am considering leaving empty sections for you to add references and contributors. Is that fine with you?

**Comment by vijay-varadarajan** [comment]
Readme Completed. Requesting review and merge

**Comment by ayaan-qadri** [comment]
Nice work @vijay-varadarajan
